import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import ThemeLayout from '../../components/Themebtn/themeLayout'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Blog Webstie',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
          <head>
    <link rel="icon" href="./assests/favicon.ico" />
    </head>
      <body className={`bg-[#F2F0DF] dark:bg-[rgb(2,8,23)] ${inter.className} font-["poppins"] transition-all duration-500`}>
        <ThemeLayout>
        {children}
        </ThemeLayout>
        </body>
    </html>
  )
}
